services:
  - type: web
    name: divine-seva
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    preDeployCommand: "php artisan migrate --force"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://divine-seva.onrender.com

      # ✅ DB ENV
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1t93lffte5s73c4ofr0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: divine_seve_db
      - key: DB_USERNAME
        value: divine_seve_db_user
      - key: DB_PASSWORD
        value: 9lf2xmNgR9q8KoeRshqlVpOAoJZQON4L

      # ✅ SESSION
      - key: SESSION_DRIVER
        value: file

      # ✅ QUEUE / CACHE
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database

      # ✅ MAIL (optional)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: goludivya10@gmail.com
      - key: MAIL_PASSWORD
        value: joadmciynqlldzwx
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: goludivya10@gmail.com
      - key: MAIL_FROM_NAME
        value: Divine Seva
