services:
  - type: web
    name: divine-seva
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://divine-seva.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1t93lffte5s73c4ofr0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: divine_seve_db
      - key: DB_USERNAME
        value: divine_seve_db_user
      - key: DB_PASSWORD
        value: 9lf2xmNgR9q8KoeRshqlVpOAoJZQON4L
